apiVersion: fn.kpt.dev/v1alpha1
kind: SetLabels
metadata: # kpt-merge: example/ghost
  name: ghost
  namespace: example
  labels:
    app.kubernetes.io/name: ghost-app
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|SetLabels|example|ghost
labels:
  app.kubernetes.io/name: ghost-app
