# Source: cert-manager/templates/webhook-config.yaml
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: cert-manager/cert-manager-webhook
  name: cert-manager-webhook
  namespace: "cert-manager"
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "webhook"
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|cert-manager|cert-manager-webhook'
data:
