# Source: cert-manager/templates/webhook-service.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: cert-manager/cert-manager-webhook
  name: cert-manager-webhook
  namespace: "cert-manager"
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.8.2"
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|cert-manager|cert-manager-webhook'
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: "https"
  selector:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "webhook"
